from yet_another_verb.exceptions.empty_argument_error import EmptyArgumentException
